sudo: required

env:
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=master
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=stable
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs

  # Using Docker from get.docker.com
  - QUIET=0 UML_FIX=0 UML_DOCKERCOMPOSE=1 BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs             DOCKER_VERSION=get.docker.com

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'cd stable             && docker build -t moul/docker-kernel-builder:stable .             && docker run moul/docker-kernel-builder:stable             echo Build succeed'
  - ./run 'cd stable-cross-armhf && docker build -t moul/docker-kernel-builder:stable-cross-armhf . && docker run moul/docker-kernel-builder:stable-cross-armhf echo Build succeed'
